server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      enabled: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ # View Resolver 설정
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/floapp?serverTimezone=Asia/Seoul
    username: floapp
    password: flo1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
